### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jbuug** [d0k3/3DS-Extended-Homebrew-Starter-Pack#2]
Hey, i am new to the home-brew scene and i was wondering do i need to do any pre-setup befor using this guide or i can put it on the sd card "depending on the firmware" and everything will just work ?

**Comment by SirNapkin1334** [comment]
This is for Arm9LoaderHax. The only things useful to you will be anything in the 3ds folder.
Simply putting it on the SD card will not help, you will need to install Boot9Strap.
Go here: https://3ds.guide
Follow it letter-for-letter, and you'll be fine.

**Comment by d0k3** [comment]
This repo is severely outdated by now and also... this is GitHub issues, not a support forum. Ask elsewhere (maybe gbatemp).
